version: '2'
services:
  web:
    build: .
    restart: always
    volumes:
      - .:/var/app
      - ~/.bash_history:/root/.bash_history
    ports:
      - "4000:3000"
    environment:
      - "RAILS_ENV=development"
    depends_on:
      - postgres

  postgres:
    image: postgres:12.1-alpine
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD="
      - "POSTGRES_DB=agendamento_vacina_development"
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
